CREATE TYPE "public"."notification_type" AS ENUM('LIKE', 'COMMENT', 'FOLLOW', 'MESSAGE', 'SYSTEM');--> statement-breakpoint
CREATE TYPE "public"."role" AS ENUM('USER', 'EDITOR', 'ADMIN');--> statement-breakpoint
CREATE TABLE "sajilo-news_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sajilo-news_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "sajilo-news_users" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sajilo-news_users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"email" varchar(255) NOT NULL,
	"username" varchar(100) NOT NULL,
	"password" varchar(255) NOT NULL,
	"first_name" varchar(100),
	"last_name" varchar(100),
	"bio" text,
	"avatar" varchar(255),
	"role" "role" DEFAULT 'USER' NOT NULL,
	"is_verified" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "sajilo-news_users_email_unique" UNIQUE("email"),
	CONSTRAINT "sajilo-news_users_username_unique" UNIQUE("username")
);
--> statement-breakpoint
CREATE INDEX "name_idx" ON "sajilo-news_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "email_idx" ON "sajilo-news_users" USING btree ("email");--> statement-breakpoint
CREATE INDEX "username_idx" ON "sajilo-news_users" USING btree ("username");