CREATE TABLE "sajilo-news_articles" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sajilo-news_articles_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(255) NOT NULL,
	"slug" varchar(255) NOT NULL,
	"content" text NOT NULL,
	"excerpt" text,
	"cover_image" varchar(255),
	"published" boolean DEFAULT false NOT NULL,
	"featured" boolean DEFAULT false NOT NULL,
	"view_count" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"author_id" integer NOT NULL,
	"category" varchar(255),
	CONSTRAINT "sajilo-news_articles_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "sajilo-news_categories" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sajilo-news_categories_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"slug" varchar(100) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "sajilo-news_categories_name_unique" UNIQUE("name"),
	CONSTRAINT "sajilo-news_categories_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "sajilo-news_category_articles" (
	"category_id" integer NOT NULL,
	"article_id" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "sajilo-news_comments" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sajilo-news_comments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"content" text NOT NULL,
	"article_id" integer NOT NULL,
	"author_id" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "sajilo-news_messages" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sajilo-news_messages_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"content" text NOT NULL,
	"sender_id" integer NOT NULL,
	"recipient_id" integer NOT NULL,
	"read" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "sajilo-news_notifications" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sajilo-news_notifications_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"type" "notification_type" NOT NULL,
	"message" varchar(255) NOT NULL,
	"read" boolean DEFAULT false NOT NULL,
	"link" varchar(255),
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "sajilo-news_tag_articles" (
	"tag_id" integer NOT NULL,
	"article_id" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "sajilo-news_tags" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sajilo-news_tags_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"slug" varchar(100) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "sajilo-news_tags_name_unique" UNIQUE("name"),
	CONSTRAINT "sajilo-news_tags_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
DROP TABLE "sajilo-news_post" CASCADE;--> statement-breakpoint
ALTER TABLE "sajilo-news_articles" ADD CONSTRAINT "sajilo-news_articles_author_id_sajilo-news_users_id_fk" FOREIGN KEY ("author_id") REFERENCES "public"."sajilo-news_users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sajilo-news_articles" ADD CONSTRAINT "sajilo-news_articles_category_sajilo-news_categories_name_fk" FOREIGN KEY ("category") REFERENCES "public"."sajilo-news_categories"("name") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sajilo-news_category_articles" ADD CONSTRAINT "sajilo-news_category_articles_category_id_sajilo-news_categories_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."sajilo-news_categories"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sajilo-news_category_articles" ADD CONSTRAINT "sajilo-news_category_articles_article_id_sajilo-news_articles_id_fk" FOREIGN KEY ("article_id") REFERENCES "public"."sajilo-news_articles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sajilo-news_comments" ADD CONSTRAINT "sajilo-news_comments_article_id_sajilo-news_articles_id_fk" FOREIGN KEY ("article_id") REFERENCES "public"."sajilo-news_articles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sajilo-news_comments" ADD CONSTRAINT "sajilo-news_comments_author_id_sajilo-news_users_id_fk" FOREIGN KEY ("author_id") REFERENCES "public"."sajilo-news_users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sajilo-news_messages" ADD CONSTRAINT "sajilo-news_messages_sender_id_sajilo-news_users_id_fk" FOREIGN KEY ("sender_id") REFERENCES "public"."sajilo-news_users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sajilo-news_messages" ADD CONSTRAINT "sajilo-news_messages_recipient_id_sajilo-news_users_id_fk" FOREIGN KEY ("recipient_id") REFERENCES "public"."sajilo-news_users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sajilo-news_notifications" ADD CONSTRAINT "sajilo-news_notifications_user_id_sajilo-news_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."sajilo-news_users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sajilo-news_tag_articles" ADD CONSTRAINT "sajilo-news_tag_articles_tag_id_sajilo-news_tags_id_fk" FOREIGN KEY ("tag_id") REFERENCES "public"."sajilo-news_tags"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sajilo-news_tag_articles" ADD CONSTRAINT "sajilo-news_tag_articles_article_id_sajilo-news_articles_id_fk" FOREIGN KEY ("article_id") REFERENCES "public"."sajilo-news_articles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "slug_idx" ON "sajilo-news_articles" USING btree ("slug");--> statement-breakpoint
CREATE INDEX "author_id_idx" ON "sajilo-news_articles" USING btree ("author_id");--> statement-breakpoint
CREATE INDEX "category_name_idx" ON "sajilo-news_categories" USING btree ("name");--> statement-breakpoint
CREATE INDEX "category_slug_idx" ON "sajilo-news_categories" USING btree ("slug");--> statement-breakpoint
CREATE INDEX "ca_category_id_idx" ON "sajilo-news_category_articles" USING btree ("category_id");--> statement-breakpoint
CREATE INDEX "ca_article_id_idx" ON "sajilo-news_category_articles" USING btree ("article_id");--> statement-breakpoint
CREATE INDEX "comment_article_id_idx" ON "sajilo-news_comments" USING btree ("article_id");--> statement-breakpoint
CREATE INDEX "comment_author_id_idx" ON "sajilo-news_comments" USING btree ("author_id");--> statement-breakpoint
CREATE INDEX "sender_id_idx" ON "sajilo-news_messages" USING btree ("sender_id");--> statement-breakpoint
CREATE INDEX "recipient_id_idx" ON "sajilo-news_messages" USING btree ("recipient_id");--> statement-breakpoint
CREATE INDEX "notification_user_id_idx" ON "sajilo-news_notifications" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "ta_tag_id_idx" ON "sajilo-news_tag_articles" USING btree ("tag_id");--> statement-breakpoint
CREATE INDEX "ta_article_id_idx" ON "sajilo-news_tag_articles" USING btree ("article_id");--> statement-breakpoint
CREATE INDEX "tag_name_idx" ON "sajilo-news_tags" USING btree ("name");--> statement-breakpoint
CREATE INDEX "tag_slug_idx" ON "sajilo-news_tags" USING btree ("slug");--> statement-breakpoint
ALTER TABLE "sajilo-news_users" DROP COLUMN "role";